{{- if .Values.serviceweb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "appname" . }}
  {{- end -}}
